USE rossi_equipamientos;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS attributes, attribute_values;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE attributes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_attribute INT DEFAULT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_attribute) REFERENCES attributes(id) ON DELETE CASCADE
);

CREATE TABLE attribute_values (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_attribute INT NOT NULL,
    value VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_attribute) REFERENCES attributes(id) ON DELETE CASCADE
);
